### ISSUE TITLE
WindowsPrintConnector Regex not working on PHP 7.3

### ISSUE THREAD

**Issue by Chris-wg** [mike42/escpos-php#670]
In WindowsPrintConnector, the regex below breaks on PHP 7.3, which made some changes to how preg_match works.

The error is 

`WindowsPrintConnector.php Line:126
"preg_match(): Compilation failed: invalid range in character class at offset 29"`

The regex is:
 
`const REGEX_SMB = "/^smb:\/\/([\s\d\w-]+(:[\s\d\w-+]+)?@)?([\d\w-]+\.)*[\d\w-]+\/([\d\w-]+\/)?[\d\w-]+(\s[\d\w-]+)*$/";`

According to https://www.debuggex.com/, the issue is with the second pattern

`(:[\s\d\w-+]+)`

I am not an expert with regex, but I find it works if the dash is removed 

`(:[\s\d\w+]+)`

I believe this regex was changed to add the interior plus sign in 

https://github.com/mike42/escpos-php/pull/392

**Comment by mike42** [comment]
I have been able to replicate this on PHP 7.3 (the unit tests catch it), so let's call it a bug. Thanks for reporting.

Unfortunately I think your change would reject lots of valid printer names, so let's keep thinking.

```php
    /**
     * Test for correct identification of bogus or non-supported Samba strings.
     */
    public function testSambaRegex()
    {
        $good = array("smb://foo/bar",
                "smb://foo/bar baz",
                "smb://bob@foo/bar",
                "smb://bob:secret@foo/bar",
                "smb://foo-computer/FooPrinter",
                "smb://foo-computer/workgroup/FooPrinter",
                "smb://foo-computer/Foo-Printer",
                "smb://foo-computer/workgroup/Foo-Printer",
                "smb://foo-computer/Foo Printer",
                "smb://foo-computer.local/Foo Printer",
                "smb://127.0.0.1/abcd"
        );
        $bad = array("",
                "http://google.com",
                "smb:/foo/bar",
                "smb://",
                "smb:///bar",
                "smb://@foo/bar",
                "smb://bob:@foo/bar",
                "smb://:secret@foo/bar",
                "smb://foo/bar/baz/quux",
                "smb://foo-computer//FooPrinter");
        foreach ($good as $item) {
            $this -> assertTrue(preg_match(WindowsPrintConnector::REGEX_SMB, $item) == 1, "Windows samba regex should pass '$item'.");
        }
        foreach ($bad as $item) {
            $this -> assertTrue(preg_match(WindowsPrintConnector::REGEX_SMB, $item) != 1, "Windows samba regex should fail '$item'.");
        }
    }
```

**Comment by mike42** [comment]
This fix has been released in v2.1 today.
